# 导航栏
menu_left:

search: 
  enable: true  # 是否使用搜索功能
  placehold: 搜索

post_excerpt_paragraph: 1
max_excerpt_words: 150


menu_right:
  - title: 主页
    path: '' 
    icon_class: ''
  - title: 博客
    path: '/archives'
  - title: 分类
    path: '/tag'
  - title: 关于
    path: /about

